name: gotogether
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev 
version: 1.0.0+1

environment:
  sdk: ^3.6.1 
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3

  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  go_router: ^14.8.0
  get_it: ^8.0.3
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  pretty_dio_logger: ^1.4.0
  mobile_scanner: ^6.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
 
  build_runner: ^2.4.15
  freezed: ^2.5.8
  flutter_lints: ^5.0.0
  freezed_annotation: ^2.4.4
 
flutter: 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
